services:
  mqtt:
    image: eclipse-mosquitto:2.0.10
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - ./mosquitto/access.acl:/mosquitto/config/acl
    ports:
      - "10000:1883"
      - "9001:9001"